"""Report Studio (spec 30 / 56).

Reports are built from stored intelligence, never regenerated by a model, so a
downloaded report always matches what the UI showed and costs nothing to
produce.

Formats are chosen for what is achievable without heavyweight dependencies:
Markdown and HTML (print-to-PDF from the browser), plus CSV and JSON for
structured data. HTML is escaped at every interpolation - report content
includes model output and fetched page titles.
"""

from __future__ import annotations

import csv
import io
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape
from typing import Any, Callable

from ..agents.analysts import composite_score
from ..domain.enums import ScoreDimension

def format_price(value: float | None, suffix: str = "") -> str:
    """Render a price, honouring the free (0) and custom (-1) sentinels."""
    if value is None:
        return "Unknown"
    if value < 0:
        return "Custom"
    if value == 0:
        return "Free"
    return f"${value:,.0f}{suffix}"


_GRADE_LABELS = {
    "verified_fact": "Verified fact",
    "strong_inference": "Strong inference",
    "weak_inference": "Weak inference",
    "ai_hypothesis": "AI hypothesis",
    "user_supplied": "User supplied",
}


@dataclass
class Report:
    title: str
    markdown: str
    filename: str

    def as_html(self) -> str:
        return markdown_to_html(self.markdown, self.title)


def _stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _slug(text: str) -> str:
    keep = [c.lower() if c.isalnum() else "-" for c in text]
    return "".join(keep).strip("-").replace("--", "-")[:60] or "report"


def _bullets(items: list[Any], empty: str = "_None recorded._") -> str:
    if not items:
        return empty
    return "\n".join(f"- {item}" for item in items)


def _evidence_footer(quality: dict[str, Any]) -> str:
    """Every report states its own evidence basis. Non-negotiable."""
    total = quality.get("total", 0)
    ratio = quality.get("evidence_backed_ratio", 0.0)
    sources = quality.get("distinct_sources", 0)

    if total == 0:
        basis = "No evidence records were produced for this analysis."
    elif sources == 0:
        basis = (
            f"**No external sources were retrieved.** All {total} claims derive from "
            "model knowledge and are hypotheses, not verified facts."
        )
    else:
        basis = (
            f"{total} claims recorded, {ratio:.0%} backed by a retrieved source, "
            f"across {sources} distinct sources."
        )

    return (
        "\n\n---\n\n## Evidence basis\n\n"
        f"{basis}\n\n"
        "Claims in this report are graded. AI-inferred findings are labelled as such "
        "and should be validated before acting on them. Market sizing figures are "
        "derived estimates showing their formulas, not measured market data.\n\n"
        f"_Generated by Product Analysis Studio on {_stamp()}._\n"
    )


# ---------------------------------------------------------------------------
# Individual reports
# ---------------------------------------------------------------------------


def executive_report(data: dict[str, Any], product: dict[str, Any]) -> Report:
    composite = data["composite"]
    scores = data["scores"]
    profile = data["profile"]
    recommendations = data["recommendations"]
    competitors = data["competitors"]

    lines = [
        f"# Executive Product Analysis: {product['name']}",
        "",
        f"_{product.get('one_liner', '')}_",
        "",
        f"**Product score: {composite['score']:.0f} / 100** "
        f"({composite['confidence']:.0%} average confidence, "
        f"{composite['coverage']:.0%} of the weighting model covered)",
        "",
    ]

    if profile:
        lines += [
            "## Summary",
            "",
            profile["summary"],
            "",
            f"**Primary problem solved:** {profile['primary_problem']}",
            "",
        ]

    if scores:
        lines += ["## Scores", "", "| Dimension | Score | Confidence | Rationale |", "|---|---|---|---|"]
        for score in scores:
            dimension = ScoreDimension(score["dimension"])
            lines.append(
                f"| {dimension.label}{' (inverted)' if score['inverted'] else ''} "
                f"| {score['score']:.0f} | {score['confidence']:.0%} "
                f"| {score['explanation'][:180].replace('|', '/')} |"
            )
        lines.append("")

    if competitors:
        lines += ["## Competitive set", "", "| Competitor | Type | Threat | Positioning |", "|---|---|---|---|"]
        for competitor in competitors[:15]:
            lines.append(
                f"| {competitor['name']} | {competitor['competitor_type']} "
                f"| {competitor['threat_level']} "
                f"| {competitor['positioning'][:120].replace('|', '/')} |"
            )
        lines.append("")

    if recommendations:
        lines += ["## Recommendations", ""]
        for rec in recommendations:
            lines += [
                f"### {rec['verdict'].replace('_', ' ').upper()}: {rec['title']}",
                "",
                f"**Problem:** {rec['problem']}",
                "",
                f"**Recommendation:** {rec['recommendation']}",
                "",
                f"**Why:** {rec['reason']}",
                "",
                f"_Effort {rec['effort'].upper()} · priority {rec['priority']} · "
                f"{rec['confidence']:.0%} confidence · decision: {rec['decision_state']}_",
                "",
            ]

    lines.append(_evidence_footer(data["quality"]))
    return Report(
        title=f"Executive Product Analysis: {product['name']}",
        markdown="\n".join(lines),
        filename=f"executive-analysis-{_slug(product['name'])}.md",
    )


def competitive_report(data: dict[str, Any], product: dict[str, Any]) -> Report:
    competitors = data["competitors"]
    lines = [f"# Competitive Intelligence Report: {product['name']}", ""]

    if not competitors:
        lines.append("_No competitors were identified in this analysis._")
    for competitor in competitors:
        lines += [
            f"## {competitor['name']}",
            "",
            f"- **Type:** {competitor['competitor_type']}",
            f"- **Threat level:** {competitor['threat_level']}",
            f"- **Website:** {competitor.get('website') or 'unknown'}",
            f"- **Target customer:** {competitor['target_customer']}",
            f"- **Positioning:** {competitor['positioning']}",
            f"- **Pricing:** {competitor['pricing_summary']}",
            f"- **Evidence grade:** {_GRADE_LABELS.get(competitor['grade'], competitor['grade'])} "
            f"({competitor['confidence']:.0%} confidence)",
            "",
            f"**Why a competitor:** {competitor['rationale']}",
            "",
            "**Strengths**",
            _bullets(competitor["strengths"]),
            "",
            "**Weaknesses**",
            _bullets(competitor["weaknesses"]),
            "",
            "**Known features**",
            _bullets(competitor["features"]),
            "",
        ]

    lines.append(_evidence_footer(data["quality"]))
    return Report(
        title=f"Competitive Intelligence: {product['name']}",
        markdown="\n".join(lines),
        filename=f"competitive-intelligence-{_slug(product['name'])}.md",
    )


def market_report(data: dict[str, Any], product: dict[str, Any]) -> Report:
    market = data["market"]
    lines = [f"# Market Analysis: {product['name']}", ""]

    if not market:
        lines.append("_No market analysis is available for this version._")
    else:
        lines += [
            f"**Market:** {market['market_definition']}",
            "",
            f"- Maturity: {market['maturity']}",
            f"- Competitive concentration: {market['competitive_concentration']}",
            "",
            "## Market sizing",
            "",
        ]
        for model in market["sizing"]:
            lines += [
                f"### {model['label']}: ${model['value_usd']:,.0f}",
                "",
                f"**Formula:** `{model['formula']}`",
                "",
                f"_Basis: {model['basis']} · {model['confidence']:.0%} confidence_",
                "",
                "**Variables**",
                _bullets(model["variables"]),
                "",
                "**Assumptions**",
                _bullets(model["assumptions"]),
                "",
            ]
        lines += [
            "## Entry barriers",
            _bullets(market["entry_barriers"]),
            "",
            "## Adjacent markets",
            _bullets(market["adjacent_markets"]),
            "",
        ]

    lines.append(_evidence_footer(data["quality"]))
    return Report(
        title=f"Market Analysis: {product['name']}",
        markdown="\n".join(lines),
        filename=f"market-analysis-{_slug(product['name'])}.md",
    )


def strategy_report(data: dict[str, Any], product: dict[str, Any]) -> Report:
    """Positioning, pricing, growth and GTM in one document."""
    lines = [f"# Strategy Report: {product['name']}", ""]

    positioning = data.get("positioning")
    if positioning:
        messaging = positioning.get("messaging", {})
        lines += [
            "## Positioning",
            "",
            f"**Recommended strategy: {positioning['recommended_strategy']}**",
            "",
            positioning["recommendation_reason"],
            "",
            f"**Positioning statement:** {messaging.get('positioning_statement', '')}",
            "",
            f"**Unique value proposition:** {messaging.get('unique_value_proposition', '')}",
            "",
            f"**Homepage headline:** {messaging.get('homepage_headline', '')}",
            "",
            f"**Subheadline:** {messaging.get('homepage_subheadline', '')}",
            "",
            f"**Elevator pitch:** {messaging.get('elevator_pitch', '')}",
            "",
            "### Options considered",
            "",
            "| Strategy | Fit | Target customer | Value proposition |",
            "|---|---|---|---|",
        ]
        for option in positioning["options"]:
            lines.append(
                f"| {option['strategy_name']} | {option['fit_score']:.0f} "
                f"| {option['target_customer'][:60].replace('|', '/')} "
                f"| {option['value_proposition'][:100].replace('|', '/')} |"
            )
        lines.append("")

    pricing = data.get("pricing")
    if pricing:
        lines += [
            "## Pricing",
            "",
            f"**Recommended model:** {pricing['recommended_model']}",
            "",
            f"**Value metric:** {pricing['value_metric']}",
            "",
            pricing["rationale"],
            "",
            "### Tiers",
            "",
            "| Tier | Price/mo | Segment | Limits |",
            "|---|---|---|---|",
        ]
        for tier in pricing["tiers"]:
            lines.append(
                f"| {tier['name']} | {format_price(tier['price_monthly_usd'])} "
                f"| {tier['target_segment'][:40].replace('|', '/')} "
                f"| {tier['limits'][:60].replace('|', '/')} |"
            )
        lines += ["", "### Assumptions", _bullets(pricing["assumptions"]), ""]

    growth = data.get("growth")
    if growth:
        lines += [
            "## Growth",
            "",
            f"**Primary motion:** {growth['primary_motion']}",
            "",
            growth["motion_rationale"],
            "",
            "### Channel priorities",
            "",
            "| Channel | Fit | Why | First experiment |",
            "|---|---|---|---|",
        ]
        for channel in growth["channels"]:
            lines.append(
                f"| {channel['channel']} | {channel['fit_score']:.0f} "
                f"| {channel['why_appropriate'][:110].replace('|', '/')} "
                f"| {channel['first_experiment'][:80].replace('|', '/')} |"
            )
        lines += [
            "",
            "### Sequencing",
            _bullets(growth["sequencing"]),
            "",
            "### Channels to avoid",
            _bullets(growth["channels_to_avoid"]),
            "",
        ]

    gtm = data.get("gtm")
    if gtm:
        lines += [
            "## Go-to-market",
            "",
            f"**Beachhead segment:** {gtm['target_segment']}",
            "",
            gtm["beachhead_rationale"],
            "",
            f"**Launch strategy:** {gtm['launch_strategy']}",
            "",
            "### Phases",
            "",
        ]
        for phase in gtm["phases"]:
            lines += [
                f"#### {phase['horizon'].replace('_', ' ').title()} "
                f"({phase['owner_role']})",
                "",
                "**Objectives**",
                _bullets(phase["objectives"]),
                "",
                "**Activities**",
                _bullets(phase["activities"]),
                "",
                "**Milestones**",
                _bullets(phase["milestones"]),
                "",
            ]
        lines += ["### Metrics", _bullets(gtm["metrics"]), "", "### Risks", _bullets(gtm["risks"]), ""]

    if len(lines) <= 2:
        lines.append("_No strategy analysis is available for this version._")

    lines.append(_evidence_footer(data["quality"]))
    return Report(
        title=f"Strategy Report: {product['name']}",
        markdown="\n".join(lines),
        filename=f"strategy-{_slug(product['name'])}.md",
    )


def evidence_report(data: dict[str, Any], product: dict[str, Any], evidence: list[dict]) -> Report:
    lines = [
        f"# Evidence Ledger: {product['name']}",
        "",
        "Every claim underpinning this analysis, with its grade, confidence and sources.",
        "",
    ]
    by_grade: dict[str, list[dict]] = {}
    for item in evidence:
        by_grade.setdefault(item["grade"], []).append(item)

    for grade in [
        "verified_fact",
        "strong_inference",
        "user_supplied",
        "weak_inference",
        "ai_hypothesis",
    ]:
        items = by_grade.get(grade, [])
        if not items:
            continue
        lines += [f"## {_GRADE_LABELS[grade]} ({len(items)})", ""]
        for item in items:
            sources = ", ".join(
                c.get("url") or c.get("title", "") for c in item.get("citations", [])
            )
            lines.append(
                f"- **{item['claim']}** — {item['confidence']:.0%} confidence, "
                f"agent `{item['agent']}`"
                + (f"  \n  Sources: {sources}" if sources else "  \n  _No source_")
            )
        lines.append("")

    lines.append(_evidence_footer(data["quality"]))
    return Report(
        title=f"Evidence Ledger: {product['name']}",
        markdown="\n".join(lines),
        filename=f"evidence-ledger-{_slug(product['name'])}.md",
    )


#: Report id -> (label, builder). Builders take (dashboard_data, product).
REPORTS: dict[str, tuple[str, Callable[..., Report]]] = {
    "executive": ("Executive Product Analysis", executive_report),
    "competitive": ("Competitive Intelligence Report", competitive_report),
    "market": ("Market Analysis", market_report),
    "strategy": ("Strategy Report (positioning, pricing, growth, GTM)", strategy_report),
}


# ---------------------------------------------------------------------------
# Format conversion
# ---------------------------------------------------------------------------


def markdown_to_html(markdown: str, title: str) -> str:
    """Render report markdown as a self-contained, printable HTML document.

    A minimal converter rather than a dependency: reports emit a known subset of
    markdown (headings, tables, bullets, bold, code spans). Every value is
    escaped before interpolation.
    """
    html_lines: list[str] = []
    in_table = False
    in_list = False

    def close_blocks() -> None:
        nonlocal in_table, in_list
        if in_table:
            html_lines.append("</tbody></table>")
            in_table = False
        if in_list:
            html_lines.append("</ul>")
            in_list = False

    def inline(text: str) -> str:
        safe = escape(text)
        # Bold and code only; applied after escaping so markup cannot be injected.
        while "**" in safe:
            safe = safe.replace("**", "<strong>", 1)
            if "**" in safe:
                safe = safe.replace("**", "</strong>", 1)
            else:
                safe += "</strong>"
        while safe.count("`") >= 2:
            safe = safe.replace("`", "<code>", 1).replace("`", "</code>", 1)
        return safe

    for raw in markdown.split("\n"):
        line = raw.rstrip()

        if not line:
            close_blocks()
            continue

        if line.startswith("|"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if all(set(c) <= {"-", ":", " "} and c for c in cells):
                continue  # separator row
            if not in_table:
                close_blocks()
                html_lines.append("<table><thead><tr>")
                html_lines += [f"<th>{inline(c)}</th>" for c in cells]
                html_lines.append("</tr></thead><tbody>")
                in_table = True
            else:
                html_lines.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in cells) + "</tr>")
            continue

        if line.startswith("- "):
            if not in_list:
                close_blocks()
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{inline(line[2:])}</li>")
            continue

        close_blocks()

        if line.startswith("#"):
            level = min(len(line) - len(line.lstrip("#")), 6)
            html_lines.append(f"<h{level}>{inline(line.lstrip('# '))}</h{level}>")
        elif line.startswith("---"):
            html_lines.append("<hr>")
        elif line.startswith("_") and line.endswith("_") and len(line) > 2:
            html_lines.append(f"<p><em>{inline(line[1:-1])}</em></p>")
        else:
            html_lines.append(f"<p>{inline(line)}</p>")

    close_blocks()
    body = "\n".join(html_lines)

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; line-height: 1.6;
         max-width: 900px; margin: 2.5rem auto; padding: 0 1.25rem; color: #1a202c; }}
  h1 {{ font-size: 1.9rem; border-bottom: 2px solid #e2e8f0; padding-bottom: .5rem; }}
  h2 {{ font-size: 1.35rem; margin-top: 2rem; color: #2d3748; }}
  h3 {{ font-size: 1.1rem; margin-top: 1.4rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: .9rem; }}
  th, td {{ border: 1px solid #e2e8f0; padding: .5rem .65rem; text-align: left;
            vertical-align: top; }}
  th {{ background: #f7fafc; font-weight: 600; }}
  code {{ background: #edf2f7; padding: .12rem .35rem; border-radius: 3px;
          font-size: .88em; }}
  hr {{ border: none; border-top: 1px solid #e2e8f0; margin: 2rem 0; }}
  em {{ color: #4a5568; }}
  @media print {{ body {{ margin: 0; max-width: none; }} }}
</style></head>
<body>
{body}
</body></html>"""


def scores_csv(scores: list[dict[str, Any]]) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(
        ["Dimension", "Score", "Inverted", "Weight", "Confidence", "Explanation", "Assumptions"]
    )
    for score in scores:
        writer.writerow(
            [
                ScoreDimension(score["dimension"]).label,
                f"{score['score']:.1f}",
                "yes" if score["inverted"] else "no",
                f"{score['weight']:.3f}",
                f"{score['confidence']:.2f}",
                score["explanation"],
                " | ".join(score.get("assumptions", [])),
            ]
        )
    return buffer.getvalue()


def competitors_csv(competitors: list[dict[str, Any]]) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(
        ["Name", "Company", "Type", "Threat", "Website", "Target customer",
         "Positioning", "Pricing", "Grade", "Confidence", "Strengths", "Weaknesses", "Features"]
    )
    for competitor in competitors:
        writer.writerow(
            [
                competitor["name"],
                competitor["company"],
                competitor["competitor_type"],
                competitor["threat_level"],
                competitor.get("website") or "",
                competitor["target_customer"],
                competitor["positioning"],
                competitor["pricing_summary"],
                competitor["grade"],
                f"{competitor['confidence']:.2f}",
                " | ".join(competitor["strengths"]),
                " | ".join(competitor["weaknesses"]),
                " | ".join(competitor["features"]),
            ]
        )
    return buffer.getvalue()


def evidence_csv(evidence: list[dict[str, Any]]) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(["Claim", "Detail", "Grade", "Confidence", "Agent", "Subject", "Sources", "Recorded"])
    for item in evidence:
        writer.writerow(
            [
                item["claim"],
                item.get("detail", ""),
                item["grade"],
                f"{item['confidence']:.2f}",
                item["agent"],
                item.get("subject_type", ""),
                " | ".join(c.get("url") or c.get("title", "") for c in item.get("citations", [])),
                item["created_at"],
            ]
        )
    return buffer.getvalue()


def full_export_json(data: dict[str, Any], product: dict[str, Any], evidence: list[dict]) -> str:
    """Complete structured export of one analysis (spec 56)."""
    payload = {
        "exported_at": _stamp(),
        "generator": "Product Analysis Studio",
        "product": {
            key: product.get(key)
            for key in (
                "id", "name", "one_liner", "category", "subcategory", "industry",
                "business_model", "market_segment", "maturity", "source_url",
            )
        },
        "analysis": data.get("analysis"),
        "composite_score": data.get("composite"),
        "scores": data.get("scores"),
        "profile": data.get("profile"),
        "competitors": data.get("competitors"),
        "market": data.get("market"),
        "customers": data.get("customers"),
        "recommendations": data.get("recommendations"),
        "positioning": data.get("positioning"),
        "pricing": data.get("pricing"),
        "growth": data.get("growth"),
        "gtm": data.get("gtm"),
        "evidence": evidence,
        "sources": data.get("sources"),
        "evidence_quality": data.get("quality"),
    }
    return json.dumps(payload, indent=2, default=str)
